<?php

// States Array

$states = array(
	'AL'=>'Albania',
	'AD'=>'Andorra',
	'AM'=>'Armenia',
	'AT'=>'Austria',
	'BY'=>'Belarus',
	'BE'=>'Belgium',
	'BA'=>'Bosnia and Herzegovina',
	'BG'=>'Bulgaria',
	'CH'=>'Switzerland',
	'CY'=>'Cyprus',
	'CZ'=>'Czech Republic',
	'DE'=>'Germany',
	'DK'=>'Denmark',
	'EE'=>'Estonia',
	'ES'=>'Spain',
	'FO'=>'Faeroe Islands',
	'FI'=>'Finland',
	'FR'=>'France',
	'GB'=>'United Kingdom',
	'GE'=>'Georgia',
	'GI'=>'Gibraltar',
	'GR'=>'Greece',
	'HU'=>'Hungary',
	'HR'=>'Croatia',
	'IE'=>'Ireland',
	'IS'=>'Iceland',
	'IT'=>'Italy',
	'LT'=>'Lithuania',
	'LU'=>'Luxembourg',
	'LV'=>'Latvia',
	'MC'=>'Monaco',
	'MK'=>'Macedonia',
	'MT'=>'Malta',
	'NO'=>'Norway',
	'NL'=>'Netherlands',
	'PL'=>'Poland',
	'PT'=>'Portugal',
	'RO'=>'Romania',
	'RU'=>'Russian Federation',
	'SE'=>'Sweden',
	'SI'=>'Slovenia',
	'SK'=>'Slovakia',
	'SR'=>'Serbia',
	'SM'=>'San Marino',
	'TR'=>'Turkey',
	'UA'=>'Ukraine',
	'VA'=>'Vatican City State'
);